-- MySQL Script generated by MySQL Workbench
-- Mon Jun  1 15:45:27 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `Albun`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Albun` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Albun` (
  `Id_Albun` INT NOT NULL,
  `NomAlbun` VARCHAR(45) NULL,
  `Año_Lanzamiento` DATE NULL,
  `Num_Canciones` VARCHAR(7) NULL,
  `Id_RolArtista` INT NOT NULL,
  PRIMARY KEY (`Id_Albun`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Artista`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Artista` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Artista` (
  `Id_RolArtista` INT NOT NULL,
  `Id_Albun` INT NULL,
  `FechaNacimiento` DATE NULL,
  `Genero` VARCHAR(45) NULL,
  `Num_seguidores` INT NULL,
  PRIMARY KEY (`Id_RolArtista`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Cancion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cancion` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Cancion` (
  `Id_Cancion` INT NOT NULL,
  `Titulo_Musica` VARCHAR(30) NULL,
  `Numero_D_reproducciones` INT NULL,
  `Nombre_Interprete` VARCHAR(45) NULL,
  `NombreCompositor` VARCHAR(45) NULL,
  `NombreProductor` VARCHAR(45) NULL,
  `Fuente` VARCHAR(45) NULL,
  `Id_Albun` INT NOT NULL,
  `Id_RolArtista` INT NOT NULL,
  PRIMARY KEY (`Id_Cancion`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `CuentaFree`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CuentaFree` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `CuentaFree` (
  `Id_UsrFree` INT NOT NULL,
  `Id_Usr` INT NOT NULL,
  PRIMARY KEY (`Id_UsrFree`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `EscuchaFree`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EscuchaFree` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `EscuchaFree` (
  `IdUsrEscuchaFree` INT NOT NULL,
  `IdPublicidad` INT NOT NULL,
  `Id_UsrFree` INT NOT NULL,
  `Id_Cancion` INT NOT NULL,
  `Id_Podcast` INT NOT NULL,
  `Tiempo_escuchando` TIME NOT NULL,
  PRIMARY KEY (`IdUsrEscuchaFree`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ListaReproduccion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ListaReproduccion` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ListaReproduccion` (
  `Id_Cancion` INT NULL,
  `NombreLista` VARCHAR(45) NULL,
  `NumeroDmusicas` VARCHAR(45) NULL,
  `Id_Usr` INT NOT NULL,
  `Id_List` INT NOT NULL,
  PRIMARY KEY (`Id_List`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ListaReproduccion_Cancion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ListaReproduccion_Cancion` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ListaReproduccion_Cancion` (
  `Id_List` INT NOT NULL,
  `Id_Cancion` INT NOT NULL,
  PRIMARY KEY (`Id_List`, `Id_Cancion`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `PREMIUM_ESCUCHA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PREMIUM_ESCUCHA` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `PREMIUM_ESCUCHA` (
  `Id_UsrPago` INT NOT NULL,
  `Id_Pago` INT NOT NULL,
  `Id_Podcast` INT NOT NULL,
  `Id_Cancion` INT NOT NULL,
  `Tiempo_Escuchando` TIME NULL,
  PRIMARY KEY (`Id_UsrPago`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Pago`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pago` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Pago` (
  `Id_Pago` INT NOT NULL,
  `TipoBanco` VARCHAR(45) NULL,
  `FechaPago` DATE NULL,
  `Id_Usr` INT NOT NULL,
  PRIMARY KEY (`Id_Pago`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `PodCast`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PodCast` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `PodCast` (
  `Id_Podcast` INT NOT NULL,
  `NombrePodcast` VARCHAR(45) NULL,
  `Duracion` VARCHAR(5) NULL,
  `Info` VARCHAR(45) NULL,
  `Podcaster_Id_RolPodcaster` INT NOT NULL,
  PRIMARY KEY (`Id_Podcast`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Podcaster`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Podcaster` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Podcaster` (
  `Id_RolPodcaster` INT NOT NULL,
  `Num_seguidores` INT NULL,
  `Info` VARCHAR(75) NULL,
  PRIMARY KEY (`Id_RolPodcaster`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Roles` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Roles` (
  `Id_Usr` INT NOT NULL,
  `Id_RolArtista` INT NOT NULL,
  `Id_RolPodcaster` INT NOT NULL,
  PRIMARY KEY (`Id_Usr`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `USUARIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `USUARIO` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `USUARIO` (
  `Id_Usr` INT NOT NULL,
  `Nombres` VARCHAR(45) NULL,
  `Apellidos` VARCHAR(45) NULL,
  `Correo` VARCHAR(45) NULL,
  `Contraseña` VARCHAR(12) NULL,
  PRIMARY KEY (`Id_Usr`));

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
